'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000';
const fmt=v=>v===null||v===undefined?'—':typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v);
function Pill({children,tone='neutral'}){return <span className={`pill ${tone}`}>{children}</span>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
export default function Home(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[running,setRunning]=useState(false);
 const load=useCallback(async()=>{try{setError('');const r=await fetch(`${API}/dashboard/overview`,{cache:'no-store'});if(!r.ok)throw new Error(await r.text());setData(await r.json())}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const runScan=async()=>{setRunning(true);setError('');try{const r=await fetch(`${API}/scan/nifty200?limit=20&enrich_news=true&send_telegram=false`,{method:'POST'});if(!r.ok)throw new Error(await r.text());await r.json();await load()}catch(e){setError(e.message)}finally{setRunning(false)}};
 const signals=data?.signals||[],intel=data?.intelligence||[],ctx=data?.market_context||{},paper=data?.performance?.paper||{},live=data?.performance?.live_simulated||{},bench=data?.benchmarks?.benchmarks||{};
 const actionable=useMemo(()=>signals.filter(s=>['LIVE','PAPER'].includes(s.classification)),[signals]);
 return <main className="shell">
  <header className="topbar"><div><div className="eyebrow">INDIA · SWING RESEARCH</div><h1>AI Swing Trading Lab</h1><p>Deterministic scanner + market intelligence + experiment journal. Human approval only.</p></div><button className="primary" onClick={runScan} disabled={running}>{running?'Running full scan…':'Run Nifty 200 scan'}</button></header>
  {error&&<div className="error">{error}</div>}{loading&&<div className="loading">Loading experiment state…</div>}
  <section className="status-grid"><div className="panel hero"><div className="panel-title">Market state</div><div className="bigline">Breadth <b>{ctx.breadth_score!=null?`${Math.round(ctx.breadth_score*100)}%`:'—'}</b></div><div className="mini-grid"><Metric label="Above 20 EMA" value={ctx.above_20ema_pct!=null?`${fmt(ctx.above_20ema_pct)}%`:'—'}/><Metric label="Above 50 DMA" value={ctx.above_50dma_pct!=null?`${fmt(ctx.above_50dma_pct)}%`:'—'}/><Metric label="Above 200 DMA" value={ctx.above_200dma_pct!=null?`${fmt(ctx.above_200dma_pct)}%`:'—'}/></div></div><div className="panel"><div className="panel-title">Experiment</div><Metric label="Live capital" value="₹1,000"/><Metric label="Max risk / trade" value="₹10"/><Metric label="Actionable journaled" value={actionable.length}/></div><div className="panel"><div className="panel-title">Connections</div><div className="connection"><span>Zerodha</span><Pill tone={data?.broker?.authenticated?'good':'warn'}>{data?.broker?.authenticated?'READ-ONLY LIVE':'KEYS PENDING'}</Pill></div><div className="connection"><span>OpenAI news</span><Pill tone={intel.length?'good':'warn'}>{intel.length?'ACTIVE':'KEY PENDING / NO DATA'}</Pill></div><div className="connection"><span>Auto trading</span><Pill tone="safe">DISABLED</Pill></div></div></section>
  <section className="section"><div className="section-head"><div><div className="eyebrow">PERFORMANCE</div><h2>Paper vs simulated live</h2></div></div><div className="metric-grid"><Metric label="Paper win rate" value={paper.win_rate_pct!=null?`${fmt(paper.win_rate_pct)}%`:'—'}/><Metric label="Paper profit factor" value={fmt(paper.profit_factor)}/><Metric label="Paper avg R" value={fmt(paper.average_r_multiple)}/><Metric label="Paper max drawdown" value={paper.max_drawdown_rupees!=null?`₹${fmt(paper.max_drawdown_rupees)}`:'—'}/><Metric label="Live-sim win rate" value={live.win_rate_pct!=null?`${fmt(live.win_rate_pct)}%`:'—'}/><Metric label="Max losing streak" value={fmt(paper.max_consecutive_losses)}/></div></section>
  <section className="two-col"><div className="panel"><div className="panel-title">Benchmarks</div>{['NIFTY50','NIFTY200'].map(k=><div className="benchmark" key={k}><div><b>{k==='NIFTY50'?'Nifty 50':'Nifty 200'}</b><small>{bench[k]?.instrument||'Zerodha read-only feed'}</small></div><div><strong>{fmt(bench[k]?.last_price)}</strong><span className={(bench[k]?.day_change_pct||0)>=0?'pos':'neg'}>{bench[k]?.day_change_pct!=null?`${fmt(bench[k].day_change_pct)}%`:'—'}</span></div></div>)}</div><div className="panel"><div className="panel-title">Leading industries · 20D</div>{(ctx.leading_industries||[]).length?(ctx.leading_industries||[]).map(x=><div className="leader" key={x.industry}><span>{x.industry}</span><b className={x.return_20d_pct>=0?'pos':'neg'}>{fmt(x.return_20d_pct)}%</b></div>):<div className="empty">Run a scan to calculate market breadth and industry leadership.</div>}</div></section>
  <section className="section"><div className="section-head"><div><div className="eyebrow">SIGNALS</div><h2>Latest journaled candidates</h2></div><Pill>{signals.length} records</Pill></div><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Class</th><th>Score</th><th>Entry zone</th><th>Stop</th><th>Target 1</th><th>R:R</th><th>Decision</th></tr></thead><tbody>{signals.slice(0,20).map(s=><tr key={s.id}><td><b>{s.symbol}</b><small>{s.name}</small></td><td><Pill tone={s.classification==='LIVE'?'good':s.classification==='PAPER'?'info':'neutral'}>{s.classification}</Pill></td><td className="score">{fmt(s.ai_score)}</td><td>{fmt(s.entry_zone_low)}–{fmt(s.entry_zone_high)}</td><td>{fmt(s.stop_loss)}</td><td>{fmt(s.target1)}</td><td>{fmt(s.risk_reward_ratio)}</td><td className="reason">{s.decision_reason}</td></tr>)}</tbody></table></div></section>
  <section className="section"><div className="section-head"><div><div className="eyebrow">LIVE INTELLIGENCE</div><h2>News & catalyst overlay</h2></div><Pill tone="safe">Never replaces risk rules</Pill></div><div className="intel-grid">{intel.length?intel.slice(0,8).map(x=><article className="intel" key={x.signal_id}><div className="intel-top"><b>{x.symbol}</b><span>Research {fmt(x.research_score)}</span></div><p>{x.summary||x.error||'No summary available.'}</p><div className="intel-meta"><span>Sentiment {fmt(x.sentiment)}</span><span>Risk {fmt(x.news_risk)}</span><span>Confidence {fmt(x.confidence)}</span></div>{x.critical_risk&&<div className="critical">Critical news risk: review before any entry.</div>}</article>):<div className="empty">Add OPENAI_API_KEY to activate sourced current-news enrichment for the top shortlist.</div>}</div></section>
  <footer>Research software · Long-only delivery · No leverage/F&O · No averaging down · No guaranteed predictions.</footer>
 </main>
}
